export const variables = {
  PLAYER_WIDTH: 50,
  PLAYER_HEIGHT: 50,
  BOARD_WIDTH: 1024,
  BOARD_HEIGHT: 768,
  INTERVAL_REFRESH: 5,
  PLAYER_MOVE_PIXELS: 1,
  SHOP_WIDTH: 428,
  SHOP_HEIGHT: 214,
  PLAYROOM_WIDTH: 214,
  PLAYROOM_HEIGHT: 214,
  INTERACTION_MARGIN: 18,
};
